name: Build projets ciblés

on:
  push:
    paths:
      - 'projet-a/**'
      - 'projet-b/**'

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      projet-a: ${{ steps.filter.outputs.projet-a }}
      projet-b: ${{ steps.filter.outputs.projet-b }}

    steps:
      - uses: actions/checkout@v3

      - name: Check which project changed
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            projet-a:
              - 'projet-a/**'
            projet-b:
              - 'projet-b/**'

  build-projet-a:
    needs: detect-changes
    if: needs.detect-changes.outputs.projet-a == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build projet-a
        run: docker build -t test-projet-a projet-a

  build-projet-b:
    needs: detect-changes
    if: needs.detect-changes.outputs.projet-b == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build projet-b
        run: docker build -t test-projet-b projet-b
